/**
 * /api/voice/request_human — ElevenLabs server tool: warm-handoff target.
 *
 * VOICE-06: Returns the human transfer target phone number and an optional
 * warm-handoff summary string generated by the conversation machine.
 *
 * Security (T-04-13):
 * - HMAC signature verified FIRST; unsigned/invalid → 401 before any parse or work.
 */

import { z } from 'zod';
import { verifyProviderSignature } from '@/lib/voice/webhook-auth';
import { env } from '@/lib/env';

// ---------------------------------------------------------------------------
// Input schema
// ---------------------------------------------------------------------------

const bodySchema = z.object({
  summary: z.string().optional(),
});

// ---------------------------------------------------------------------------
// Route handler
// ---------------------------------------------------------------------------

export async function POST(req: Request): Promise<Response> {
  // 1. Verify signature FIRST — 401 before any other work (T-04-13)
  const rawBody = await req.text();
  const verified = verifyProviderSignature('default', rawBody, req.headers);
  if (!verified) {
    return new Response(null, { status: 401 });
  }

  // 2. Parse + validate (summary is optional)
  let summary: string | undefined;
  try {
    const json: unknown = JSON.parse(rawBody);
    const result = bodySchema.safeParse(json);
    if (!result.success) {
      return Response.json({ error: 'Invalid request body' }, { status: 400 });
    }
    summary = result.data.summary;
  } catch {
    return Response.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  // 3. Return warm-handoff target (VOICE-06)
  return Response.json({
    transferTo: env.CONTACT_PHONE,
    summary: summary ?? null,
  });
}
